### ISSUE TITLE
Pirated repos and software.

### ISSUE THREAD

**Issue by Shadowgar** [jlippold/tweakCompatible#100443]
Are we just allowing everything on here? I noticed a pirated flagging system but it claims only mods can report it.  And it appears not much is being done by mods with all of the pirated stuff on here.

**Comment by jlippold** [comment]
What do you see thats pirated, I can delete or if you're up to you can mod. in the future @ me or I dont see it

**Comment by Shadowgar** [comment]
@jlippold I can report through the TC but last time I did I was told I wasn’t a mod. There are multiple items posted through various repos to bypass the banned repos here.

**Comment by jlippold** [comment]
Yea, I can make you a mod if you want to do the job, or you can tell me directly what needs banning and i'll do it for you
