### ISSUE TITLE
`Safari Plus` partially working on iOS 12.4

### ISSUE THREAD

**Issue by mmoroni** [jlippold/tweakCompatible#101658]
{
  "packageId": "com.opa334.safariplus",
  "action": "partially working",
  "userInfo": {
    "arch32": false,
    "packageId": "com.opa334.safariplus",
    "deviceId": "iPhone7,2",
    "url": "http://cydia.saurik.com/package/com.opa334.safariplus/",
    "iOSVersion": "12.4",
    "packageVersionIndexed": false,
    "packageName": "Safari Plus",
    "category": "Tweaks",
    "repository": "BigBoss",
    "name": "Safari Plus",
    "installed": "1.7.6",
    "packageIndexed": true,
    "packageStatusExplaination": "A matching version of this tweak for this iOS version could not be found. Please submit a review if you choose to install.",
    "id": "com.opa334.safariplus",
    "commercial": false,
    "packageInstalled": true,
    "tweakCompatVersion": "tweakcompatible-zebra-1.1.2",
    "shortDescription": "Various enhancements to Safari!",
    "latest": "1.7.6",
    "author": "opa334",
    "packageStatus": "Unknown"
  },
  "base64": "eyJhcmNoMzIiOmZhbHNlLCJwYWNrYWdlSWQiOiJjb20uc2FtZ2lzYW5pbmphLnR3ZWFrY29tcGF0aWJsZS16ZWJyYSIsImRldmljZUlkIjoiaVBob25lNywyIiwidXJsIjoiaHR0cDpcL1wvY3lkaWEuc2F1cmlrLmNvbVwvcGFja2FnZVwvY29tLnNhbWdpc2FuaW5qYS50d2Vha2NvbXBhdGlibGUtemVicmFcLyIsInBhY2thZ2VOYW1lIjoiVHdlYWtDb21wYXRpYmxlIGZvciBaZWJyYSIsInBhY2thZ2VWZXJzaW9uSW5kZXhlZCI6dHJ1ZSwiaU9TVmVyc2lvbiI6IjEyLjQiLCJjYXRlZ29yeSI6IlR3ZWFrcyIsInJlcG9zaXRvcnkiOiJTYW1nX2lzX2FfTmluamEncyBSZXBvIiwibmFtZSI6IlR3ZWFrQ29tcGF0aWJsZSBmb3IgWmVicmEiLCJpbnN0YWxsZWQiOiIxLjEuMiIsInBhY2thZ2VJbnN0YWxsZWQiOnRydWUsInBhY2thZ2VTdGF0dXNFeHBsYWluYXRpb24iOiJUaGlzIHBhY2thZ2UgdmVyc2lvbiBoYXMgYmVlbiBtYXJrZWQgYXMgV29ya2luZyBiYXNlZCBvbiBmZWVkYmFjayBmcm9tIHVzZXJzIGluIHRoZSBjb21tdW5pdHkuIFRoZSBjdXJyZW50IHBvc2l0aXZlIHJhdGluZyBpcyAxMDAlIHdpdGggNyB3b3JraW5nIHJlcG9ydHMuIiwiaWQiOiJjb20uc2FtZ2lzYW5pbmphLnR3ZWFrY29tcGF0aWJsZS16ZWJyYSIsImNvbW1lcmNpYWwiOmZhbHNlLCJwYWNrYWdlSW5kZXhlZCI6dHJ1ZSwidHdlYWtDb21wYXRWZXJzaW9uIjoidHdlYWtjb21wYXRpYmxlLXplYnJhLTEuMS4yIiwic2hvcnREZXNjcmlwdGlvbiI6IkFkZHMgVHdlYWtDb21wYXRpYmxlIHRvIFplYnJhISIsImxhdGVzdCI6IjEuMS4yIiwiYXV0aG9yIjoiU2FtZ19pc19hX05pbmphIiwicGFja2FnZVN0YXR1cyI6IldvcmtpbmcifQ==",
  "chosenStatus": "partially working",
  "notes": "Most of its features are working but some are not, e.g. Replace Search Engine..."
}

**Comment by ann0see** [comment]
@jlippold I think the user used an old version of tweak compatible. Maybe that’s why this issue is still open?

**Comment by jlippold** [comment]
no, they edited the post body
