### ISSUE TITLE
Can’t report tweak as working/broken 

### ISSUE THREAD

**Issue by MattTheNinjaMan** [jlippold/tweakCompatible#10813]
I might be doing something wrong however when I go I to a tweak on cydia (in my case right now, Twitter dark mode 0.0.4) to report it as working, I get a server error page and then after clicking back I get “thank you for submitting this”. If I am doing something wrong please let me know so I can fix myself for next time

**Comment by Goldvag** [comment]
I got that too
I ran iCleaner and then it worked fine
Maybe corrupt cookies?

**Comment by robertybob** [comment]
Before you tap "Next", tap the GitHub logo to sign in. It should then work for you.

**Comment by CydiaUser420** [comment]
I have had this problem on multipul devices here is how i fixed it.  Go to any tweak and click info and find where anyone reported the tweak as working or not working it doesn't matter. Click the blue link the says "reported this tweak". That will bring you to the github page where in the top right corner you can click the plus to add an issue. That will give you a prompt to login to github. After you login you can back out and report tweaks as working or not working. Its a pain to go through this process hopefully the developer fixes this soon but this process totally works in the mean time

**Comment by MattTheNinjaMan** [comment]
Robertybob thank you so much bro
