### ISSUE TITLE
Working, not working page Never Loads?

### ISSUE THREAD

**Issue by gatekeeper1122** [jlippold/tweakCompatible#108899]
I have the following devices below & when i try to make a post on a tweak if its working or not the page never loads the results are in the picture at the bottom

Devices 
All Devices Run IOS 13.2.2
-Iphone 8+ Red Edition
-Iphone 8+ Space Grey
-Iphone 6s Pink
-Ipad 6 Gen

https://imgur.com/a/Eov53qi

**Comment by Shadowgar** [comment]
What are you trying to submit?

**Comment by ilovemywater** [comment]
I think that I partly understand your problem. Can you please provide a video?
