### ISSUE TITLE
[NOBUG] Thank you for your awesome work!

### ISSUE THREAD

**Issue by MikeeI** [jlippold/tweakCompatible#117697]
I think you get way too less "thank yous" for your work. 

I'm just so grateful to use it and profit from your dedication.

Just a thank you. 😊

![200](https://user-images.githubusercontent.com/13944905/75364672-5ddbc000-58bc-11ea-9d43-a085646ee615.gif)

**Comment by jlippold** [comment]
thanks dude :)
