### ISSUE TITLE
Electra Cydia tweak issues iPhone silent

### ISSUE THREAD

**Issue by alincampan** [jlippold/tweakCompatible#12021]
I’ve installed a cydia tweak and now my iPhone has gone silent. When I get a phone call or text it doesn’t make any sound , it’s completely gone and the phone isn’t on mute.

Which tweak could be causing this to happen, when off jailbreak mode works fine as it should be makes sound and when in jailbreak it’s silent.

I’m really not happy with this, please help

**Comment by jlippold** [comment]
No idea, ask in /r/jailbreak
