### ISSUE TITLE
Allow us to be able to update reviews 

### ISSUE THREAD

**Issue by silentshotghost** [jlippold/tweakCompatible#12043]
Add a update review button so we can update them. Cause currently they automatically get marked as duplicate

**Comment by Qaragholy** [comment]
Good

**Comment by jlippold** [comment]
I’m pretty sure the most recent review takes precedence over the old, doesn't it?

**Comment by silentshotghost** [comment]
@jlippold for me it has been marking them as duplicate

**Comment by jlippold** [comment]
10-4, i'll fix this with the other stuff im planning

**Comment by fbfb016** [comment]
😁

**Comment by fbfb016** [comment]
😁

**Comment by fbfb016** [comment]
good

**Comment by troozksa07** [comment]
#`
Duplicate of #`
