### ISSUE TITLE
This issue is being closed because your review was accepted into the tweakCompatible website.

### ISSUE THREAD

**Issue by moody5588** [jlippold/tweakCompatible#121578]
This issue is being closed because your review was accepted into the tweakCompatible website. 
Tweak developers do not monitor or fix issues submitted via this repo.
If you have an issue with a tweak, contact the developer via another method.

_Originally posted by @tweakCompatible-bot in https://github.com/jlippold/tweakCompatible/issues/119467#issuecomment-598655290_

**Comment by miwgmail** [comment]
Hi
