### ISSUE TITLE
Scrolling through versions while viewing the website within cydia is almost impossible

### ISSUE THREAD

**Issue by tommoses** [jlippold/tweakCompatible#12218]
To recreate:
- Look at a tweak that has been marked as working or not working in cydia
- Click tweakCompatible's Info button
- Try scrolling through different versions, you should see the scrollbox close itself

Here are some videos showing it happening both with and without NoMoreSmallApps enabled:
https://youtu.be/--_J4hl_STM
https://youtu.be/4Yygo2FCPwc

I should note that you can easily scroll through the versions in safari or chrome

**Comment by silentshotghost** [comment]
must be tweak interfering cause i have no problem

**Comment by jlippold** [comment]
Im not sure whats causing that either, but im almost done redesigning that entire page, so it wont matter.

Thanks for reporting

**Comment by jlippold** [comment]
This is fixed
