### ISSUE TITLE
Favicon for the website

### ISSUE THREAD

**Issue by KMamedoff** [jlippold/tweakCompatible#12452]

**Comment by jlippold** [comment]
U interested in making one and posting it here?

**Comment by KMamedoff** [comment]
[Actually that tick icon is good enough](https://imgur.com/a/Phaywr0)

**Comment by Macley-Kun** [comment]
https://realfavicongenerator.net/
Might come on handy. If you made an icon you can use this tool to get the necessary code. Recommend this one :-)
