### ISSUE TITLE
`Glance` not working on iOS 13.5

### ISSUE THREAD

**Issue by edmechem** [jlippold/tweakCompatible#126107]
```
{
  "packageId": "com.rpetrich.glance",
  "action": "notworking",
  "userInfo": {
    "arch32": false,
    "packageId": "com.rpetrich.glance",
    "deviceId": "iPhone11,6",
    "url": "http://cydia.saurik.com/package/com.rpetrich.glance/",
    "packageName": "Glance",
    "packageVersionIndexed": false,
    "iOSVersion": "13.5",
    "category": "Tweaks",
    "repository": "rpetrich repo",
    "name": "Glance",
    "installed": "0.1",
    "packageInstalled": true,
    "packageStatusExplaination": "This tweak has not been reviewed. Please submit a review if you choose to install.",
    "id": "com.rpetrich.glance",
    "commercial": false,
    "packageIndexed": false,
    "tweakCompatVersion": "tweakcompatible-zebra-1.1.5",
    "shortDescription": "Peek at your wallpaper by swiping up",
    "latest": "0.1",
    "author": "Ryan Petrich ",
    "packageStatus": "Unknown"
  },
  "base64": "eyJhcmNoMzIiOmZhbHNlLCJwYWNrYWdlSWQiOiJjb20ucnBldHJpY2guZ2xhbmNlIiwiZGV2aWNlSWQiOiJpUGhvbmUxMSw2IiwidXJsIjoiaHR0cDpcL1wvY3lkaWEuc2F1cmlrLmNvbVwvcGFja2FnZVwvY29tLnJwZXRyaWNoLmdsYW5jZVwvIiwicGFja2FnZU5hbWUiOiJHbGFuY2UiLCJwYWNrYWdlVmVyc2lvbkluZGV4ZWQiOmZhbHNlLCJpT1NWZXJzaW9uIjoiMTMuNSIsImNhdGVnb3J5IjoiVHdlYWtzIiwicmVwb3NpdG9yeSI6InJwZXRyaWNoIHJlcG8iLCJuYW1lIjoiR2xhbmNlIiwiaW5zdGFsbGVkIjoiMC4xIiwicGFja2FnZUluc3RhbGxlZCI6dHJ1ZSwicGFja2FnZVN0YXR1c0V4cGxhaW5hdGlvbiI6IlRoaXMgdHdlYWsgaGFzIG5vdCBiZWVuIHJldmlld2VkLiBQbGVhc2Ugc3VibWl0IGEgcmV2aWV3IGlmIHlvdSBjaG9vc2UgdG8gaW5zdGFsbC4iLCJpZCI6ImNvbS5ycGV0cmljaC5nbGFuY2UiLCJjb21tZXJjaWFsIjpmYWxzZSwicGFja2FnZUluZGV4ZWQiOmZhbHNlLCJ0d2Vha0NvbXBhdFZlcnNpb24iOiJ0d2Vha2NvbXBhdGlibGUtemVicmEtMS4xLjUiLCJzaG9ydERlc2NyaXB0aW9uIjoiUGVlayBhdCB5b3VyIHdhbGxwYXBlciBieSBzd2lwaW5nIHVwIiwibGF0ZXN0IjoiMC4xIiwiYXV0aG9yIjoiUnlhbiBQZXRyaWNoICIsInBhY2thZ2VTdGF0dXMiOiJVbmtub3duIn0=",
  "chosenStatus": "not working",
  "notes": ""
}
```

**Comment by miwgmail** [comment]
> ```
> 
> {
> 
>   "packageId": "com.rpetrich.glance",
> 
>   "action": "notworking",
> 
>   "userInfo": {
> 
>     "arch32": false,
> 
>     "packageId": "com.rpetrich.glance",
> 
>     "deviceId": "iPhone11,6",
> 
>     "url": "http://cydia.saurik.com/package/com.rpetrich.glance/",
> 
>     "packageName": "Glance",
> 
>     "packageVersionIndexed": false,
> 
>     "iOSVersion": "13.5",
> 
>     "category": "Tweaks",
> 
>     "repository": "rpetrich repo",
> 
>     "name": "Glance",
> 
>     "installed": "0.1",
> 
>     "packageInstalled": true,
> 
>     "packageStatusExplaination": "This tweak has not been reviewed. Please submit a review if you choose to install.",
> 
>     "id": "com.rpetrich.glance",
> 
>     "commercial": false,
> 
>     "packageIndexed": false,
> 
>     "tweakCompatVersion": "tweakcompatible-zebra-1.1.5",
> 
>     "shortDescription": "Peek at your wallpaper by swiping up",
> 
>     "latest": "0.1",
> 
>     "author": "Ryan Petrich ",
> 
>     "packageStatus": "Unknown"
> 
>   },
> 
>   "base64": "eyJhcmNoMzIiOmZhbHNlLCJwYWNrYWdlSWQiOiJjb20ucnBldHJpY2guZ2xhbmNlIiwiZGV2aWNlSWQiOiJpUGhvbmUxMSw2IiwidXJsIjoiaHR0cDpcL1wvY3lkaWEuc2F1cmlrLmNvbVwvcGFja2FnZVwvY29tLnJwZXRyaWNoLmdsYW5jZVwvIiwicGFja2FnZU5hbWUiOiJHbGFuY2UiLCJwYWNrYWdlVmVyc2lvbkluZGV4ZWQiOmZhbHNlLCJpT1NWZXJzaW9uIjoiMTMuNSIsImNhdGVnb3J5IjoiVHdlYWtzIiwicmVwb3NpdG9yeSI6InJwZXRyaWNoIHJlcG8iLCJuYW1lIjoiR2xhbmNlIiwiaW5zdGFsbGVkIjoiMC4xIiwicGFja2FnZUluc3RhbGxlZCI6dHJ1ZSwicGFja2FnZVN0YXR1c0V4cGxhaW5hdGlvbiI6IlRoaXMgdHdlYWsgaGFzIG5vdCBiZWVuIHJldmlld2VkLiBQbGVhc2Ugc3VibWl0IGEgcmV2aWV3IGlmIHlvdSBjaG9vc2UgdG8gaW5zdGFsbC4iLCJpZCI6ImNvbS5ycGV0cmljaC5nbGFuY2UiLCJjb21tZXJjaWFsIjpmYWxzZSwicGFja2FnZUluZGV4ZWQiOmZhbHNlLCJ0d2Vha0NvbXBhdFZlcnNpb24iOiJ0d2Vha2NvbXBhdGlibGUtemVicmEtMS4xLjUiLCJzaG9ydERlc2NyaXB0aW9uIjoiUGVlayBhdCB5b3VyIHdhbGxwYXBlciBieSBzd2lwaW5nIHVwIiwibGF0ZXN0IjoiMC4xIiwiYXV0aG9yIjoiUnlhbiBQZXRyaWNoICIsInBhY2thZ2VTdGF0dXMiOiJVbmtub3duIn0=",
> 
>   "chosenStatus": "not working",
> 
>   "notes": ""
> 
> }
> 
> ```
