### ISSUE TITLE
`ConfirmRotate` working on iOS 13.5

### ISSUE THREAD

**Issue by IsoscelesTriangle** [jlippold/tweakCompatible#126182]
```
{
  "packageId": "com.cardboardface.confirmrotate",
  "action": "working",
  "userInfo": {
    "arch32": false,
    "packageId": "com.cardboardface.confirmrotate",
    "deviceId": "iPhone12,5",
    "url": "http://cydia.saurik.com/package/com.cardboardface.confirmrotate/",
    "iOSVersion": "13.5",
    "packageVersionIndexed": false,
    "packageName": "ConfirmRotate",
    "category": "Tweaks",
    "repository": "Packix",
    "name": "ConfirmRotate",
    "installed": "1.2",
    "packageIndexed": true,
    "packageStatusExplaination": "A matching version of this tweak for this iOS version could not be found. Please submit a review if you choose to install.",
    "id": "com.cardboardface.confirmrotate",
    "commercial": true,
    "packageInstalled": true,
    "tweakCompatVersion": "0.1.5",
    "shortDescription": "Ask before rotating!",
    "latest": "1.2.1",
    "author": "CardboardFace",
    "packageStatus": "Unknown"
  },
  "base64": "eyJhcmNoMzIiOmZhbHNlLCJwYWNrYWdlSWQiOiJjb20uY2FyZGJvYXJkZmFjZS5jb25maXJtcm90YXRlIiwiZGV2aWNlSWQiOiJpUGhvbmUxMiw1IiwidXJsIjoiaHR0cDpcL1wvY3lkaWEuc2F1cmlrLmNvbVwvcGFja2FnZVwvY29tLmNhcmRib2FyZGZhY2UuY29uZmlybXJvdGF0ZVwvIiwiaU9TVmVyc2lvbiI6IjEzLjUiLCJwYWNrYWdlVmVyc2lvbkluZGV4ZWQiOmZhbHNlLCJwYWNrYWdlTmFtZSI6IkNvbmZpcm1Sb3RhdGUiLCJjYXRlZ29yeSI6IlR3ZWFrcyIsInJlcG9zaXRvcnkiOiJQYWNraXgiLCJuYW1lIjoiQ29uZmlybVJvdGF0ZSIsImluc3RhbGxlZCI6IjEuMiIsInBhY2thZ2VJbmRleGVkIjp0cnVlLCJwYWNrYWdlU3RhdHVzRXhwbGFpbmF0aW9uIjoiQSBtYXRjaGluZyB2ZXJzaW9uIG9mIHRoaXMgdHdlYWsgZm9yIHRoaXMgaU9TIHZlcnNpb24gY291bGQgbm90IGJlIGZvdW5kLiBQbGVhc2Ugc3VibWl0IGEgcmV2aWV3IGlmIHlvdSBjaG9vc2UgdG8gaW5zdGFsbC4iLCJpZCI6ImNvbS5jYXJkYm9hcmRmYWNlLmNvbmZpcm1yb3RhdGUiLCJjb21tZXJjaWFsIjp0cnVlLCJwYWNrYWdlSW5zdGFsbGVkIjp0cnVlLCJ0d2Vha0NvbXBhdFZlcnNpb24iOiIwLjEuNSIsInNob3J0RGVzY3JpcHRpb24iOiJBc2sgYmVmb3JlIHJvdGF0aW5nISIsImxhdGVzdCI6IjEuMi4xIiwiYXV0aG9yIjoiQ2FyZGJvYXJkRmFjZSIsInBhY2thZ2VTdGF0dXMiOiJVbmtub3duIn0=",
  "chosenStatus": "working",
  "notes": ""
}
```

**Comment by miwgmail** [comment]
> ```
> 
> {
> 
>   "packageId": "com.cardboardface.confirmrotate",
> 
>   "action": "working",
> 
>   "userInfo": {
> 
>     "arch32": false,
> 
>     "packageId": "com.cardboardface.confirmrotate",
> 
>     "deviceId": "iPhone12,5",
> 
>     "url": "http://cydia.saurik.com/package/com.cardboardface.confirmrotate/",
> 
>     "iOSVersion": "13.5",
> 
>     "packageVersionIndexed": false,
> 
>     "packageName": "ConfirmRotate",
> 
>     "category": "Tweaks",
> 
>     "repository": "Packix",
> 
>     "name": "ConfirmRotate",
> 
>     "installed": "1.2",
> 
>     "packageIndexed": true,
> 
>     "packageStatusExplaination": "A matching version of this tweak for this iOS version could not be found. Please submit a review if you choose to install.",
> 
>     "id": "com.cardboardface.confirmrotate",
> 
>     "commercial": true,
> 
>     "packageInstalled": true,
> 
>     "tweakCompatVersion": "0.1.5",
> 
>     "shortDescription": "Ask before rotating!",
> 
>     "latest": "1.2.1",
> 
>     "author": "CardboardFace",
> 
>     "packageStatus": "Unknown"
> 
>   },
> 
>   "base64": "eyJhcmNoMzIiOmZhbHNlLCJwYWNrYWdlSWQiOiJjb20uY2FyZGJvYXJkZmFjZS5jb25maXJtcm90YXRlIiwiZGV2aWNlSWQiOiJpUGhvbmUxMiw1IiwidXJsIjoiaHR0cDpcL1wvY3lkaWEuc2F1cmlrLmNvbVwvcGFja2FnZVwvY29tLmNhcmRib2FyZGZhY2UuY29uZmlybXJvdGF0ZVwvIiwiaU9TVmVyc2lvbiI6IjEzLjUiLCJwYWNrYWdlVmVyc2lvbkluZGV4ZWQiOmZhbHNlLCJwYWNrYWdlTmFtZSI6IkNvbmZpcm1Sb3RhdGUiLCJjYXRlZ29yeSI6IlR3ZWFrcyIsInJlcG9zaXRvcnkiOiJQYWNraXgiLCJuYW1lIjoiQ29uZmlybVJvdGF0ZSIsImluc3RhbGxlZCI6IjEuMiIsInBhY2thZ2VJbmRleGVkIjp0cnVlLCJwYWNrYWdlU3RhdHVzRXhwbGFpbmF0aW9uIjoiQSBtYXRjaGluZyB2ZXJzaW9uIG9mIHRoaXMgdHdlYWsgZm9yIHRoaXMgaU9TIHZlcnNpb24gY291bGQgbm90IGJlIGZvdW5kLiBQbGVhc2Ugc3VibWl0IGEgcmV2aWV3IGlmIHlvdSBjaG9vc2UgdG8gaW5zdGFsbC4iLCJpZCI6ImNvbS5jYXJkYm9hcmRmYWNlLmNvbmZpcm1yb3RhdGUiLCJjb21tZXJjaWFsIjp0cnVlLCJwYWNrYWdlSW5zdGFsbGVkIjp0cnVlLCJ0d2Vha0NvbXBhdFZlcnNpb24iOiIwLjEuNSIsInNob3J0RGVzY3JpcHRpb24iOiJBc2sgYmVmb3JlIHJvdGF0aW5nISIsImxhdGVzdCI6IjEuMi4xIiwiYXV0aG9yIjoiQ2FyZGJvYXJkRmFjZSIsInBhY2thZ2VTdGF0dXMiOiJVbmtub3duIn0=",
> 
>   "chosenStatus": "working",
> 
>   "notes": ""
> 
> }
> ]()
