### ISSUE TITLE
`LowPowerLock` working on iOS 13.5

### ISSUE THREAD

**Issue by VictorxD70** [jlippold/tweakCompatible#126350]
```
{
  "packageId": "me.jjolano.lowpowerlock",
  "action": "working",
  "userInfo": {
    "arch32": false,
    "packageId": "me.jjolano.lowpowerlock",
    "deviceId": "iPhone8,1",
    "url": "http://cydia.saurik.com/package/me.jjolano.lowpowerlock/",
    "iOSVersion": "13.5",
    "packageVersionIndexed": true,
    "packageName": "LowPowerLock",
    "category": "Tweaks",
    "repository": "jjolano's iOS Tweaks",
    "name": "LowPowerLock",
    "installed": "0.0.2",
    "packageIndexed": true,
    "packageStatusExplaination": "A matching version of this tweak for this iOS version could not be found. Please submit a review if you choose to install.",
    "id": "me.jjolano.lowpowerlock",
    "commercial": false,
    "packageInstalled": true,
    "tweakCompatVersion": "0.1.5",
    "shortDescription": "Enables Low Power Mode automatically while your device is locked.",
    "latest": "0.0.2",
    "author": "jjolano",
    "packageStatus": "Unknown"
  },
  "base64": "eyJhcmNoMzIiOmZhbHNlLCJwYWNrYWdlSWQiOiJtZS5qam9sYW5vLmxvd3Bvd2VybG9jayIsImRldmljZUlkIjoiaVBob25lOCwxIiwidXJsIjoiaHR0cDpcL1wvY3lkaWEuc2F1cmlrLmNvbVwvcGFja2FnZVwvbWUuampvbGFuby5sb3dwb3dlcmxvY2tcLyIsImlPU1ZlcnNpb24iOiIxMy41IiwicGFja2FnZVZlcnNpb25JbmRleGVkIjp0cnVlLCJwYWNrYWdlTmFtZSI6Ikxvd1Bvd2VyTG9jayIsImNhdGVnb3J5IjoiVHdlYWtzIiwicmVwb3NpdG9yeSI6Impqb2xhbm8ncyBpT1MgVHdlYWtzIiwibmFtZSI6Ikxvd1Bvd2VyTG9jayIsImluc3RhbGxlZCI6IjAuMC4yIiwicGFja2FnZUluZGV4ZWQiOnRydWUsInBhY2thZ2VTdGF0dXNFeHBsYWluYXRpb24iOiJBIG1hdGNoaW5nIHZlcnNpb24gb2YgdGhpcyB0d2VhayBmb3IgdGhpcyBpT1MgdmVyc2lvbiBjb3VsZCBub3QgYmUgZm91bmQuIFBsZWFzZSBzdWJtaXQgYSByZXZpZXcgaWYgeW91IGNob29zZSB0byBpbnN0YWxsLiIsImlkIjoibWUuampvbGFuby5sb3dwb3dlcmxvY2siLCJjb21tZXJjaWFsIjpmYWxzZSwicGFja2FnZUluc3RhbGxlZCI6dHJ1ZSwidHdlYWtDb21wYXRWZXJzaW9uIjoiMC4xLjUiLCJzaG9ydERlc2NyaXB0aW9uIjoiRW5hYmxlcyBMb3cgUG93ZXIgTW9kZSBhdXRvbWF0aWNhbGx5IHdoaWxlIHlvdXIgZGV2aWNlIGlzIGxvY2tlZC4iLCJsYXRlc3QiOiIwLjAuMiIsImF1dGhvciI6Impqb2xhbm8iLCJwYWNrYWdlU3RhdHVzIjoiVW5rbm93biJ9",
  "chosenStatus": "working",
  "notes": ""
}
```

**Comment by Ayedalqahtani** [comment]
> ```
> 
> {
> 
>   "packageId": "me.jjolano.lowpowerlock",
> 
>   "action": "working",
> 
>   "userInfo": {
> 
>     "arch32": false,
> 
>     "packageId": "me.jjolano.lowpowerlock",
> 
>     "deviceId": "iPhone8,1",
> 
>     "url": "http://cydia.saurik.com/package/me.jjolano.lowpowerlock/",
> 
>     "iOSVersion": "13.5",
> 
>     "packageVersionIndexed": true,
> 
>     "packageName": "LowPowerLock",
> 
>     "category": "Tweaks",
> 
>     "repository": "jjolano's iOS Tweaks",
> 
>     "name": "LowPowerLock",
> 
>     "installed": "0.0.2",
> 
>     "packageIndexed": true,
> 
>     "packageStatusExplaination": "A matching version of this tweak for this iOS version could not be found. Please submit a review if you choose to install.",
> 
>     "id": "me.jjolano.lowpowerlock",
> 
>     "commercial": false,
> 
>     "packageInstalled": true,
> 
>     "tweakCompatVersion": "0.1.5",
> 
>     "shortDescription": "Enables Low Power Mode automatically while your device is locked.",
> 
>     "latest": "0.0.2",
> 
>     "author": "jjolano",
> 
>     "packageStatus": "Unknown"
> 
>   },
> 
>   "base64": "eyJhcmNoMzIiOmZhbHNlLCJwYWNrYWdlSWQiOiJtZS5qam9sYW5vLmxvd3Bvd2VybG9jayIsImRldmljZUlkIjoiaVBob25lOCwxIiwidXJsIjoiaHR0cDpcL1wvY3lkaWEuc2F1cmlrLmNvbVwvcGFja2FnZVwvbWUuampvbGFuby5sb3dwb3dlcmxvY2tcLyIsImlPU1ZlcnNpb24iOiIxMy41IiwicGFja2FnZVZlcnNpb25JbmRleGVkIjp0cnVlLCJwYWNrYWdlTmFtZSI6Ikxvd1Bvd2VyTG9jayIsImNhdGVnb3J5IjoiVHdlYWtzIiwicmVwb3NpdG9yeSI6Impqb2xhbm8ncyBpT1MgVHdlYWtzIiwibmFtZSI6Ikxvd1Bvd2VyTG9jayIsImluc3RhbGxlZCI6IjAuMC4yIiwicGFja2FnZUluZGV4ZWQiOnRydWUsInBhY2thZ2VTdGF0dXNFeHBsYWluYXRpb24iOiJBIG1hdGNoaW5nIHZlcnNpb24gb2YgdGhpcyB0d2VhayBmb3IgdGhpcyBpT1MgdmVyc2lvbiBjb3VsZCBub3QgYmUgZm91bmQuIFBsZWFzZSBzdWJtaXQgYSByZXZpZXcgaWYgeW91IGNob29zZSB0byBpbnN0YWxsLiIsImlkIjoibWUuampvbGFuby5sb3dwb3dlcmxvY2siLCJjb21tZXJjaWFsIjpmYWxzZSwicGFja2FnZUluc3RhbGxlZCI6dHJ1ZSwidHdlYWtDb21wYXRWZXJzaW9uIjoiMC4xLjUiLCJzaG9ydERlc2NyaXB0aW9uIjoiRW5hYmxlcyBMb3cgUG93ZXIgTW9kZSBhdXRvbWF0aWNhbGx5IHdoaWxlIHlvdXIgZGV2aWNlIGlzIGxvY2tlZC4iLCJsYXRlc3QiOiIwLjAuMiIsImF1dGhvciI6Impqb2xhbm8iLCJwYWNrYWdlU3RhdHVzIjoiVW5rbm93biJ9",
> 
>   "chosenStatus": "working",
> 
>   "notes": ""
> 
> }
> 
> ```
