### ISSUE TITLE
`Hub` not working on iOS 13.5

### ISSUE THREAD

**Issue by taichi202** [jlippold/tweakCompatible#127142]
```
{
  "packageId": "com.twickd.dylan-west.hub",
  "action": "notworking",
  "userInfo": {
    "arch32": false,
    "packageId": "com.twickd.dylan-west.hub",
    "deviceId": "iPhone12,1",
    "url": "http://cydia.saurik.com/package/com.twickd.dylan-west.hub/",
    "iOSVersion": "13.5",
    "packageVersionIndexed": false,
    "packageName": "Hub",
    "category": "Tweaks",
    "repository": "Twickd",
    "name": "Hub",
    "installed": "1.1",
    "packageIndexed": false,
    "packageStatusExplaination": "This tweak has not been reviewed. Please submit a review if you choose to install.",
    "id": "com.twickd.dylan-west.hub",
    "commercial": true,
    "packageInstalled": true,
    "tweakCompatVersion": "0.1.5",
    "shortDescription": "Quick access and multitasking.",
    "latest": "1.1",
    "author": "Dylan West",
    "packageStatus": "Unknown"
  },
  "base64": "eyJhcmNoMzIiOmZhbHNlLCJwYWNrYWdlSWQiOiJjb20udHdpY2tkLmR5bGFuLXdlc3QuaHViIiwiZGV2aWNlSWQiOiJpUGhvbmUxMiwxIiwidXJsIjoiaHR0cDpcL1wvY3lkaWEuc2F1cmlrLmNvbVwvcGFja2FnZVwvY29tLnR3aWNrZC5keWxhbi13ZXN0Lmh1YlwvIiwiaU9TVmVyc2lvbiI6IjEzLjUiLCJwYWNrYWdlVmVyc2lvbkluZGV4ZWQiOmZhbHNlLCJwYWNrYWdlTmFtZSI6Ikh1YiIsImNhdGVnb3J5IjoiVHdlYWtzIiwicmVwb3NpdG9yeSI6IlR3aWNrZCIsIm5hbWUiOiJIdWIiLCJpbnN0YWxsZWQiOiIxLjEiLCJwYWNrYWdlSW5kZXhlZCI6ZmFsc2UsInBhY2thZ2VTdGF0dXNFeHBsYWluYXRpb24iOiJUaGlzIHR3ZWFrIGhhcyBub3QgYmVlbiByZXZpZXdlZC4gUGxlYXNlIHN1Ym1pdCBhIHJldmlldyBpZiB5b3UgY2hvb3NlIHRvIGluc3RhbGwuIiwiaWQiOiJjb20udHdpY2tkLmR5bGFuLXdlc3QuaHViIiwiY29tbWVyY2lhbCI6dHJ1ZSwicGFja2FnZUluc3RhbGxlZCI6dHJ1ZSwidHdlYWtDb21wYXRWZXJzaW9uIjoiMC4xLjUiLCJzaG9ydERlc2NyaXB0aW9uIjoiUXVpY2sgYWNjZXNzIGFuZCBtdWx0aXRhc2tpbmcuIiwibGF0ZXN0IjoiMS4xIiwiYXV0aG9yIjoiRHlsYW4gV2VzdCIsInBhY2thZ2VTdGF0dXMiOiJVbmtub3duIn0l=",
  "chosenStatus": "not working",
  "notes": "Show blank page in iphone11"
}
```

**Comment by Aboood412** [comment]
> ```
> 
> {
> 
>   "packageId": "com.twickd.dylan-west.hub",
> 
>   "action": "notworking",
> 
>   "userInfo": {
> 
>     "arch32": false,
> 
>     "packageId": "com.twickd.dylan-west.hub",
> 
>     "deviceId": "iPhone12,1",
> 
>     "url": "http://cydia.saurik.com/package/com.twickd.dylan-west.hub/",
> 
>     "iOSVersion": "13.5",
> 
>     "packageVersionIndexed": false,
> 
>     "packageName": "Hub",
> 
>     "category": "Tweaks",
> 
>     "repository": "Twickd",
> 
>     "name": "Hub",
> 
>     "installed": "1.1",
> 
>     "packageIndexed": false,
> 
>     "packageStatusExplaination": "This tweak has not been reviewed. Please submit a review if you choose to install.",
> 
>     "id": "com.twickd.dylan-west.hub",
> 
>     "commercial": true,
> 
>     "packageInstalled": true,
> 
>     "tweakCompatVersion": "0.1.5",
> 
>     "shortDescription": "Quick access and multitasking.",
> 
>     "latest": "1.1",
> 
>     "author": "Dylan West",
> 
>     "packageStatus": "Unknown"
> 
>   },
> 
>   "base64": "eyJhcmNoMzIiOmZhbHNlLCJwYWNrYWdlSWQiOiJjb20udHdpY2tkLmR5bGFuLXdlc3QuaHViIiwiZGV2aWNlSWQiOiJpUGhvbmUxMiwxIiwidXJsIjoiaHR0cDpcL1wvY3lkaWEuc2F1cmlrLmNvbVwvcGFja2FnZVwvY29tLnR3aWNrZC5keWxhbi13ZXN0Lmh1YlwvIiwiaU9TVmVyc2lvbiI6IjEzLjUiLCJwYWNrYWdlVmVyc2lvbkluZGV4ZWQiOmZhbHNlLCJwYWNrYWdlTmFtZSI6Ikh1YiIsImNhdGVnb3J5IjoiVHdlYWtzIiwicmVwb3NpdG9yeSI6IlR3aWNrZCIsIm5hbWUiOiJIdWIiLCJpbnN0YWxsZWQiOiIxLjEiLCJwYWNrYWdlSW5kZXhlZCI6ZmFsc2UsInBhY2thZ2VTdGF0dXNFeHBsYWluYXRpb24iOiJUaGlzIHR3ZWFrIGhhcyBub3QgYmVlbiByZXZpZXdlZC4gUGxlYXNlIHN1Ym1pdCBhIHJldmlldyBpZiB5b3UgY2hvb3NlIHRvIGluc3RhbGwuIiwiaWQiOiJjb20udHdpY2tkLmR5bGFuLXdlc3QuaHViIiwiY29tbWVyY2lhbCI6dHJ1ZSwicGFja2FnZUluc3RhbGxlZCI6dHJ1ZSwidHdlYWtDb21wYXRWZXJzaW9uIjoiMC4xLjUiLCJzaG9ydERlc2NyaXB0aW9uIjoiUXVpY2sgYWNjZXNzIGFuZCBtdWx0aXRhc2tpbmcuIiwibGF0ZXN0IjoiMS4xIiwiYXV0aG9yIjoiRHlsYW4gV2VzdCIsInBhY2thZ2VTdGF0dXMiOiJVbmtub3duIn0l=",
> 
>   "chosenStatus": "not working",
> 
>   "notes": "Show blank page in iphone11"
> 
> }
> 
> ```

**Comment by Aboood412** [comment]
Thanks
