### ISSUE TITLE
`AppCake` working on iOS 12.4.8

### ISSUE THREAD

**Issue by realsly2** [jlippold/tweakCompatible#132024]
Removed content

**Comment by jlippold** [comment]
This report contains piracy and will not be accepted, please refrain from submitting piracy related reports. `HackYouriPhone`

**Comment by jlippold** [comment]
This report contains piracy and will not be accepted, please refrain from submitting piracy related reports. `HackYouriPhone`

**Comment by jlippold** [comment]
This report contains piracy and will not be accepted, please refrain from submitting piracy related reports. `HackYouriPhone`

**Comment by jlippold** [comment]
This report contains piracy and will not be accepted, please refrain from submitting piracy related reports. `HackYouriPhone`
