### ISSUE TITLE
New update of tweakcompatible freezing cydia. 

### ISSUE THREAD

**Issue by draxlrose** [jlippold/tweakCompatible#1536]
Tweakcompatible is causing cydia to freeze when i go into installed apps(thats the only location i checked before removing the tweak). It was working before you just pushed the update in the last hour. I was able to report to your compatibility page but after upgrading to new version I couldn’t do that anymore. I am on Electra 1.0.1 and ios 11.0.2 on ipad 2017.

**Comment by aliniti** [comment]
Yea same here..

**Comment by notexe** [comment]
Same issue here. I have temporary downgraded back to 0.0.3 for now.

Running IOS 11.0.1

**Comment by draxlrose** [comment]
@notexe Is there anyway to install the downgraded version after already uninstalling the new version?

**Comment by notexe** [comment]
Download the deb file for it: http://apt.thebigboss.org/repofiles/cydia/debs2.0/tweakcompatible_0.0.3.deb

Copy that to your device using SFTP to any folder. /var/root/ is the folder I copied it to.
SSH into your phone and type: dpkg -i /path/to/tweakcompatible_0.0.3.deb

That will install the previous version of Tweak Compatible. You will need to repspring manually.

**Comment by inkrypted** [comment]
Same

**Comment by jlippold** [comment]
I think this is related to https://github.com/ElectraJailbreak/cydia/issues/4

**Comment by jlippold** [comment]
For you guys who are saying it's freezing, I noticed a similar thing after my very first install, but after waiting for a bit the white screen went away and all was fine. Can anyone confirm this for me? That the white screen is temporary? If electra doesnt get an update for this, I might have to go back to the button thing, but the inline buttons are so much better

**Comment by notexe** [comment]
Yes it’s just temporary. I left it sitting there for 2 minutes and it loaded in the end, after that I could instantly view any other tweak fine.

**Comment by jlippold** [comment]
Yea i just rebooted my phone, and noticed the freeze again after re-jailbreaking, but I just waited and then its good again. It seems like the freeze is once per re-jailbreak.

Im not sure if it's worth gutting the inline buttons to fix this freeze

**Comment by notexe** [comment]
I can live with waiting, since I do prefer the inline buttons as well. As long as it’s only after each reboot I can deal with it.

**Comment by notexe** [comment]
Okay it’s making me wait again, I haven’t rebooted yet. I think if Cydia is closed for a while and then reopened, you will have to wait again.

**Comment by t41k1** [comment]
I am same, after re-jailbreaking it, it is freezing.
I think inline buttons is far better because I can check Tweak Status easily.

**Comment by t41k1** [comment]
As I use...
Cydia froze not only after re-jailbreaking.
It froze after removing repos and installing tweaks.

**Comment by jlippold** [comment]
Ok i'm working on an alternative approach

**Comment by yettoexist** [comment]
> For you guys who are saying it's freezing, I noticed a similar thing after my very first install, but after waiting for a bit the white screen went away and all was fine. Can anyone confirm this for me? That the white screen is temporary? If electra doesnt get an update for this, I might have to go back to the button thing, but the inline buttons are so much better

I had the same issue, but the loading circle was still active in the status bar. I waited it out 2-3 mins and it finally loaded, each tweak I searched for after that had less of a delay.

**Comment by draxlrose** [comment]
The temporary white screen thing is correct. I reinstall the same version of the tweak and waited for a couple of minutes for it to load. And now it seems to be working fine. The wait time reduces. I will post any further complications if any.

**Comment by draxlrose** [comment]
I think it’s worth keeping this version even with a little freeze time. It’s much better.

**Comment by Wowfunhappy** [comment]
I would like to provide my two cents that I really preferred the overlay. The freezing of the current method is quite extensive at times, for me.

**Comment by jlippold** [comment]
Can you guys try this build and let me know if it's better now? https://github.com/jlippold/tweakCompatible/releases/tag/0.0.5a

**Comment by jlippold** [comment]
fixed with 0.0.5

**Comment by draxlrose** [comment]
Sorry im not too familiar with sideloading apps. Please push the update to Cydia.
