### ISSUE TITLE
Use overlay to avoid webview injection

### ISSUE THREAD

**Issue by jlippold** [jlippold/tweakCompatible#1654]
Workaround for https://github.com/jlippold/tweakCompatible/issues/1536

**Comment by draxlrose** [comment]
What is overlay?

**Comment by draxlrose** [comment]
I have an unrelated question I couldn’t find an answer to. How do you add the name of the device On your tweak status report when reporting from tweakcompatible?

**Comment by jlippold** [comment]
it reads the device type off the phone, you can't change it

**Comment by draxlrose** [comment]
Oh i guess it cannot identify ipads?

**Comment by jlippold** [comment]
this is completed in 0.0.5
