### ISSUE TITLE
broke cydia

### ISSUE THREAD

**Issue by Reynbow** [jlippold/tweakCompatible#1904]
Soooo I installed this to try to help confirm a tweak that doesn't work. 
Now my Cydia is broken since installing it. 
Whenever I tap to go to a tweaks detail screen, the screen is completely blank and Cydia is frozen. Can't tap any button.

So my Cydia is now completely broken and I have no way to remove this tweak or install/remove any other tweak.

**Comment by Suzuha** [comment]
reported already https://github.com/jlippold/tweakCompatible/issues/1536
