### ISSUE TITLE
Loading Error on iPhone7 Jailbreak 11.3.1

### ISSUE THREAD

**Issue by Pir8pete** [jlippold/tweakCompatible#19256]
Getting an error when loading your newest version of iBlacklist 11.1 on iOS jailbreak (Electra) version 11.3.1 with an iPhone 7.  I took screenshots of the loading error , see attached.  Also the splash screen looks distorted.

**Comment by Pir8pete** [comment]
![img_0004](https://user-images.githubusercontent.com/25421389/42469177-fcf091ac-8384-11e8-8bed-f42510135f64.PNG)
![img_0003](https://user-images.githubusercontent.com/25421389/42469178-fd0278d6-8384-11e8-9db6-cfc31cff8a43.PNG)

**Comment by jlippold** [comment]
You have to contact the iBlacklist dev or ask your question on reddit, this repo is for tweakCompatible issues / reports only.
