### ISSUE TITLE
[0.0.5] Compatibility info overlaps package description webview

### ISSUE THREAD

**Issue by arjanvlek** [jlippold/tweakCompatible#2100]
The new version 0.0.5 fixes the freezing of Cydia (yay!), but has another issue: 
The new compatibility bar at the bottom overlaps the package description webview. This makes it impossible to use the bottom options ("Show package contents" in case of an already installed package, or the website buttons of a not-yet installed package). The package description webview should be shrunken so you can scroll through the entire tweak description page when tweakcompatible is active.

![img_0192](https://user-images.githubusercontent.com/10106652/36865848-024b02e0-1d91-11e8-8706-3120a112f72f.PNG)
![img_0191](https://user-images.githubusercontent.com/10106652/36865850-026766b0-1d91-11e8-9477-942dd671a2b1.PNG)
![img_0190](https://user-images.githubusercontent.com/10106652/36865851-02821050-1d91-11e8-8191-0fbe975a70c2.PNG)
![img_0193](https://user-images.githubusercontent.com/10106652/36865853-02a276a6-1d91-11e8-8b7c-542a58377815.PNG)

**Comment by jlippold** [comment]
Yup agreed, I'll try to resize it. Thanks

**Comment by jlippold** [comment]
fixed in 0.0.6
