### ISSUE TITLE
iJackOff (version 1.2) working on iOS 11.3.1 and below

### ISSUE THREAD

**Issue by CodeyMoore** [jlippold/tweakCompatible#22288]
Can someone please remove all reports of my app not working and list it as "working but you need to add https://codeymoore.github.io/ into your repos and update to version 1.2" 

Thank you in advanced

**Comment by jlippold** [comment]
Hey @CodeyMoore,

I can't manually mark something as working, but I can totally remove your tweak from the website. Should I remove it entirely?

**Comment by CodeyMoore** [comment]
Mark the 1.2 version as working and the 1.0.0 version if you can mark that as not working but they can install my repo above ^^ and download the 1.2 version.
If you could do that it would be great thank you

Cheers

**Comment by jlippold** [comment]
That happens automatically when they use tweakcompatible. If anyone downloads 1.2 they mark is as working, then other users can benefit from that review, but I'm not really in the business of overwriting what users report.
