### ISSUE TITLE
Will new update for tweak compatible be coming soon on Cydia?

### ISSUE THREAD

**Issue by draxlrose** [jlippold/tweakCompatible#2232]
It seems you were able to fix the freeing issues. Looking forward to the new update on cydia? When could we hope to see it on Cydia?

**Comment by jlippold** [comment]
Thats up to bigboss, it's been submitted. IF you cant wait, install the deb from here https://github.com/jlippold/tweakCompatible/releases/tag/0.0.6

**Comment by jlippold** [comment]
ohh the version that fixes the freezing is on bigboss now (0.0.5). 0.0.6 is pending

**Comment by draxlrose** [comment]
Thank you! You are awesome! Install 0.0.5 now.
