### ISSUE TITLE
Tweakcompatible crashing when clicking submit issue on github via cydia tweak.

### ISSUE THREAD

**Issue by draxlrose** [jlippold/tweakCompatible#2542]
@jlippold the new update 0.0.5 and 0.0.6 on tweakcompatible is crashing while submitting status of tweaks. The crash occurs when the gihub page opens and i press the submit issue button. It opens in the browser within safari, so when i click it safari crashes. This started with 0.0.5. I hoped it would be fixed n 0.0.6 and i managed do one submission before it happned again. Is this isolated to me or are others reporting similar issues?

Here is a video of a screenrecording:

https://youtu.be/hEqC_2_0v0w

**Comment by draxlrose** [comment]
Its working on n off now. Somehow if i put the cursor on the box with all the code before submission, then it doesn’t seem to crash sometimes.

**Comment by jlippold** [comment]
This is the first I'm hearing of this. Whats odd about this is that it doesn't seem to be "tweak related". It's just a webpage submitting data, I'm not sure why would that crash. I've never tested on an iPad, could that be why? Do you have a phone you can test with? What version if iOS? Are you running any safari related tweaks that might be causing it?

Man, I wish crash reporter worked so I could see a stacktrace or something.

**Comment by draxlrose** [comment]
Im in ios 110.2. I don’t have a jailbroken phone. My iphone is in ios 11.2.2 sadly. I have safari plus running bjt the crash was occurring before i installed that as well. I do have content blockers running on safari. I will see if anything works to prevent crashes.

**Comment by draxlrose** [comment]
The problem persists. But the tweak is still useful to me to get info on compatibility status. I just cannot report the status myself. Anyway thanks for this great tweak!

**Comment by draxlrose** [comment]
Update: crashing seems to have stopped. I was able to report about a dozen or so tweaks without issues. I have updated to electra 1.0.4 and updated tweak injector too. Don’t know what fixd the issue but im glad it is fixed.

**Comment by jlippold** [comment]
cool :-)
