### ISSUE TITLE
Ipad air 2 cellular unknown device

### ISSUE THREAD

**Issue by CydiaUser420** [jlippold/tweakCompatible#2985]
I submitted about 40 tweaks today that worked on 10.2 on my ipad air 2 cellular and it says unknown device on all of them. Just wanted to clear up my identifier is ipad 5,4

**Comment by veteranatgames2** [comment]
You could change the title of your submission, that might work.

**Comment by jlippold** [comment]
no, it just needs to be labeled, i got it
