### ISSUE TITLE
TweakCompatible not compatible with iPad 

### ISSUE THREAD

**Issue by seanbperiod** [jlippold/tweakCompatible#3511]
I installed TweakCompatible on iPad Mini 4 with 11.1.2 on Electra, and there's no way to view it/activate the function in Cydia.

**Comment by jlippold** [comment]
Do you have some tweak called little X installed? I've heard that it breaks this tweak somehow

**Comment by seanbperiod** [comment]
Nope. I only have appinst, AppSync, and PPSSPP installed.

**Comment by veteranatgames2** [comment]
It works completely fine on my iPad Air wifi with iOS 11.1.2 on electra

**Comment by ElectraRC** [comment]
Lol u fucked up
