### ISSUE TITLE
32bit vs 64bit

### ISSUE THREAD

**Issue by xevidos** [jlippold/tweakCompatible#354]
Hello, I love the idea for your tweak.  I was wondering if you have implemented a 32bit/64bit option when submitting/searching.  Because if you have 10.2 on 32bit some tweaks may be compatible but not compatible with 10.2 on 64 bit and vice versa.

**Comment by jlippold** [comment]
I don't have a good way to do this but if you view the [package page](https://jlippold.github.io/tweakCompatible/package.html#!/org.thebigboss.automa/details/) you can see what kind of device the user used when submitting. I think from there, you can decide whether it was tested on 32 or 64

**Comment by Mc-muffin** [comment]
Can't you use the same device information to know if it is 32 or 64 bit?

**Comment by jlippold** [comment]
yes but I don't have a way to count reports by architecture. Let me think about this some more

**Comment by jlippold** [comment]
I have 32 bit outcomes being calculated BUT I can't update the tweak's code yet because I'm no longer jailbroken, so I can't test. I try to finish this once that ios11 JB drops with cydia

**Comment by xevidos** [comment]
If you would like I could help you test it.  I am a developer as well, I would just need to know what you would like me to do.

**Comment by jlippold** [comment]
ohh ok sweet, I have a few changes I'd like to make, but I'm scared to because I can't test it. Let me blind code some fixes, and i'll package a deb

**Comment by jlippold** [comment]
Hey @xevidos submit a few reviews with this deb https://github.com/jlippold/tweakCompatible/releases/tag/0.0.4

**Comment by jlippold** [comment]
Thank you @xevidos I saw your submissions, which means I didnt break anything ;)
I just need to find a user on a 32bit device to try one. I can ask on reddit for that

**Comment by xevidos** [comment]
I went ahead and sent 3 packages through.  No issues on my end so far.  However it may be a good idea not to have to form submission open in a new tab.  Also I have a 32bit device I can test on in a few hours if you would like

**Comment by jlippold** [comment]
Thanks @xevidos ! I don't know if I can stop the new tab thing, is there an alternative to `[UIApplication sharedApplication] openURL:` that you know of?

And yes, if you can do a few 32-bit submissions later today, it would be great. I don't know if I am properly checking for 32-bit.

**Comment by xevidos** [comment]
I went ahead and submitted on two different 32bit devices one on 10.3.3 the other on 6.1.6.  

The plugin did not work on 6.1.6 but that is expected.  I will test on 7.x, 8.x, and 9.3.5 asap.

When testing on ios 10.3.3 every time I hit next, github would open in a new tab and then show oops 500 error.  I believe that would be an error upon receiving data from your form.  I tried it again on a 64bit device to see if github had blocked your page due to number of visits or bandwidth restraints and the page worked on 64bit.

Also I did not mean the initial opening of the form.  I just meant when you hit next on the the submit tweak review page it opens the issue in another tab on github then shows the success page in the original tab.  It may be good to just have the success page and add a link to the github report just so that way every time someone submits a tweak review it doesn't open two new tabs on their device.  Or maybe you could have the page redirect them after they submit a new issue.  I am not sure about github's functionality with that though.

In regards to that I tend to use it as:
[[UIApplication sharedApplication] openURL:[NSURL URLWithString:@"URL Here."]];
But no I don't really know off the top of my head a better way to do it.

**Comment by jlippold** [comment]
Thanks for the help @xevidos 

If I had to guess, maybe there's a forbidden character thats being passed that causes the 500 when I'm sending the details to the github issue. It's just a simple form that I'm building https://github.com/jlippold/tweakCompatible/blob/master/docs/submit.html#L77-L80, so I'm not sure how 32 bit architecture could bomb anything. Did you try to submit the same tweak from 64bit? Does this link work from 32bit? https://github.com/jlippold/tweakCompatible/issues/new?title=foo&body=bar If so, it's gotta be something silly, like an emoji in the device name or something?

**Comment by xevidos** [comment]
I apologize it was my fault I wasn't signed into github on the 32bit device.  Sorry about that.  I have gone ahead and sent a report.

**Comment by xevidos** [comment]
I tested today and the tweak works on 8 but not on 7.  To be exact I tested on 8.4.1 and 7.1.2.

**Comment by jlippold** [comment]
heh I remember you tatsh, from xsellize way back when

**Comment by jlippold** [comment]
Im gonna close this since 32bit is supported in 0.0.4
