### ISSUE TITLE
Please Add iOS 9 Compatiblity

### ISSUE THREAD

**Issue by leuldereje** [jlippold/tweakCompatible#36061]
It really is sad that you dont have iOS 9 Support.
There are still plenty of users who are on iOS 9 & can benefit from your tweak.

Please add support for it. i, personally have two devices on iOS 9 and i can contribute greatly.

Thank you

@jlippold (Notifying)

**Comment by leuldereje** [comment]
Check this:

https://www.reddit.com/r/jailbreak/comments/92zoml/comment/e3any4r?st=JK8Q7PAQ&sh=c07efbca

**Comment by jlippold** [comment]
cool so its working on iOS9. Thanks for posting back
