### ISSUE TITLE
Option to see results from similar iOS versions?

### ISSUE THREAD

**Issue by Wowfunhappy** [jlippold/tweakCompatible#3943]
I'm on iOS 11.1.1. Most iOS 11 Jailbreak users are on 11.1.2.

As a result, I see very few tweak compatibility results in Cydia, even though a test result from 11.1.2 is VERY likely to be accurate to 11.1.1 as well. In order to get any useful data, I need to click the "Info" button.

Would it be possible to add an option to display results from similar iOS versions? Ideally, which iOS versions are displayed would be user selectable.

**Comment by jlippold** [comment]
Good idea. I’m not positive how to implement this, but let me think about it some more

**Comment by Relisiuol** [comment]
Maybe an option to verify iOS version in different ways?

- Strict (actually coded/default option for updates)
- Minor (check 11.1.x)
- Major (check 11.x, bad idea I think)

**Comment by jlippold** [comment]
This is fixed in the next version
