### ISSUE TITLE
IOS Version Won’t Change In Settings

### ISSUE THREAD

**Issue by BrianLeek** [jlippold/tweakCompatible#39808]
I am on IOS 11.3 and I go to change my IOS version for tweakCompatibility via settings but when I change it to IOS 11.3.1 and close Cydia and reopen it nothing changed why is this? I even tried a respring but still nothing.

Also when you are viewing a tweak on the website where it says repo it just displays the repos name shouldn’t it be the URL?

**Comment by jlippold** [comment]
Changing the ios version only changes the status indicator on the main table list, so those little checkmarks would now match iOS 11.3.1 in your example.

The repo address is only available if a moderator submits the address, so not all repo's have it
