### ISSUE TITLE
option to change our previous submissions

### ISSUE THREAD

**Issue by deucetresthugz** [jlippold/tweakCompatible#53941]
Can you please add ability to user to go back and edit our tweak compatibility submissions? For example: I installed a tweak that was working at first, but issues arised with more useage. I had already submitted it as compatible but have no option to go back and change it. This would definitely make your tweak much more accurate for mistakes such as this. Thanks!

**Comment by jlippold** [comment]
I think you just have to resubmit and it overwrites the previous review
