### ISSUE TITLE
Can't open "tweakcompatible" github inside of cydia?

### ISSUE THREAD

**Issue by gatekeeper1122** [jlippold/tweakCompatible#73076]
when ever i try to access the "tweakcompatible" ever since 3 days ago it has been giving error 500 here https://i.imgur.com/MQa8Sln.png i thought it would be fixed after a day or so but still shows it before it was working fine & connecting fine before 3 days ago when i first heard about this very useful tweak

**Comment by Nixuge** [comment]
Sign in to github in the in-app browser
