### ISSUE TITLE
Please open to iOS 7-8

### ISSUE THREAD

**Issue by AppleTweaker420** [jlippold/tweakCompatible#73291]
I know iOS 7-8 are very legacy now but some people with legacy devices still could use the information. Like for example anyone who updates rocket bootstrap to the latest beta on iOS 7.1.2 will go into safe mode. These incidents are extremely rare however they do happen from time to time. I know for a fact that this tweak used to work on those firmwares and I think it would be neat to see it again. Thanks for your time mate cheers thanks for the great tweak

**Comment by jlippold** [comment]
Try one of the older releases here: https://github.com/jlippold/tweakCompatible/releases

**Comment by AppleTweaker420** [comment]
Thank you very much I can’t believe I didn’t try this lol
