### ISSUE TITLE
Sort public facing list

### ISSUE THREAD

**Issue by rparanson** [jlippold/tweakCompatible#744]
Would be great to be able to sort this list by date and not just alphabetically.  Thanks for considering!

https://jlippold.github.io/tweakCompatible/

Rick

**Comment by jlippold** [comment]
I've been ignoring this project while we all wait for cydia on 11.1.2

Once that happens, i'll start to improve on this project again

**Comment by rparanson** [comment]
Thank you for the update.  Appreciate it!  -Rick



Rick Aranson
raranson@gmail.com
678-404-1818

   - www.linkedin.com/in/raranson/
