### ISSUE TITLE
Iphone 7 plus restarting randomly 

### ISSUE THREAD

**Issue by talebctg** [jlippold/tweakCompatible#80435]
I have jailbroken my iphone 7 plus running iOS 12.1.2 woth unc0ver, my phone restarting randomly when even i check my snapchat stories, or i open photo gallery from messenger, or i swipe on springboard, phone restarts randomly and i have to jailbreak again, sometimes the phones restarts several times, can anyone please help me with a proper solution

Tweaks i am using
Bettercc
Bettersettings
Boxy 3
Carrierizer
Notracking+
Notifica
Snowboard
Tweakcompitable
Youtubed

Almost all of them are working on 12.1.2 ,  checked on tweakcompitable

PLEASE HELP

**Comment by Nixuge** [comment]
Post this on Reddit
