### ISSUE TITLE
Zebra compatibility?

### ISSUE THREAD

**Issue by nathanielcwm** [jlippold/tweakCompatible#90452]
Maybe tweakcompatible could work in zebra.

**Comment by jlippold** [comment]
possibly when iOS 13 JB drops i'll have a look

**Comment by Samgisaninja** [comment]
https://github.com/Samgisaninja/tweakcompatible-zebra

**Comment by jlippold** [comment]
u want to submit a pull samg? i'll gladly merge, publish and give u credit for the update

**Comment by jlippold** [comment]
or does your update lose cydia compatibility? if so it makes sense to have a fork

**Comment by Samgisaninja** [comment]
I don't provide Cydia compatibility in my tweak. It's not a fork, it just uses the tweakcompatible database.

**Comment by jlippold** [comment]
sounds good, i'll continue to keep the DB importing new stuff. Thanks for writing it

**Comment by Samgisaninja** [comment]
np, and if there's anything I can/should do on my end to help you with that, lmk
