### ISSUE TITLE
`Signing Certificate` working on iOS 12.4

### ISSUE THREAD

**Issue by ygzok** [jlippold/tweakCompatible#95063]
```
{
  "packageId": "signing-certificate",
  "action": "working",
  "userInfo": {
    "arch32": false,
    "packageId": "signing-certificate",
    "deviceId": "iPhone10,6",
    "url": "http://cydia.saurik.com/package/signing-certificate/",
    "iOSVersion": "12.4",
    "packageVersionIndexed": true,
    "packageName": "Signing Certificate",
    "category": "System",
    "repository": "(null)",
    "name": "Signing Certificate",
    "installed": "0.0.1",
    "packageIndexed": true,
    "packageStatusExplaination": "A matching version of this tweak for this iOS version could not be found. Please submit a review if you choose to install.",
    "id": "signing-certificate",
    "commercial": false,
    "packageInstalled": true,
    "tweakCompatVersion": "0.1.5",
    "shortDescription": "A Certificate to sign things with",
    "latest": "0.0.1",
    "author": "None",
    "packageStatus": "Unknown"
  },
  "base64": "eyJhcmNoMzIiOmZhbHNlLCJwYWNrYWdlSWQiOiJzaWduaW5nLWNlcnRpZmljYXRlIiwiZGV2aWNlSWQiOiJpUGhvbmUxMCw2IiwidXJsIjoiaHR0cDpcL1wvY3lkaWEuc2F1cmlrLmNvbVwvcGFja2FnZVwvc2lnbmluZy1jZXJ0aWZpY2F0ZVwvIiwiaU9TVmVyc2lvbiI6IjEyLjQiLCJwYWNrYWdlVmVyc2lvbkluZGV4ZWQiOnRydWUsInBhY2thZ2VOYW1lIjoiU2lnbmluZyBDZXJ0aWZpY2F0ZSIsImNhdGVnb3J5IjoiU3lzdGVtIiwicmVwb3NpdG9yeSI6IihudWxsKSIsIm5hbWUiOiJTaWduaW5nIENlcnRpZmljYXRlIiwiaW5zdGFsbGVkIjoiMC4wLjEiLCJwYWNrYWdlSW5kZXhlZCI6dHJ1ZSwicGFja2FnZVN0YXR1c0V4cGxhaW5hdGlvbiI6IkEgbWF0Y2hpbmcgdmVyc2lvbiBvZiB0aGlzIHR3ZWFrIGZvciB0aGlzIGlPUyB2ZXJzaW9uIGNvdWxkIG5vdCBiZSBmb3VuZC4gUGxlYXNlIHN1Ym1pdCBhIHJldmlldyBpZiB5b3UgY2hvb3NlIHRvIGluc3RhbGwuIiwiaWQiOiJzaWduaW5nLWNlcnRpZmljYXRlIiwiY29tbWVyY2lhbCI6ZmFsc2UsInBhY2thZ2VJbnN0YWxsZWQiOnRydWUsInR3ZWFrQ29tcGF0VmVyc2lvbiI6IjAuMS41Iiwic2hvcnREZXNjcmlwdGlvbiI6IkEgQ2VydGlmaWNhdGUgdG8gc2lnbiB0aGluZ3Mgd2l0aCIsImxhdGVzdCI6IjAuMC4xIiwiYXV0aG9yIjoiTm9uZSIsInBhY2thZ2VTdGF0dXMiOiJVbmtub3duIn0=",
  "chosenStatus": "working",
  "notes": ""
}
```

**Comment by hadi93** [comment]
> {
>   "packageId": "signing-certificate",
>   "action": "working",
>   "userInfo": {
>     "arch32": false,
>     "packageId": "signing-certificate",
>     "deviceId": "iPhone10,6",
>     "url": "http://cydia.saurik.com/package/signing-certificate/",
>     "iOSVersion": "12.4",
>     "packageVersionIndexed": true,
>     "packageName": "Signing Certificate",
>     "category": "System",
>     "repository": "(null)",
>     "name": "Signing Certificate",
>     "installed": "0.0.1",
>     "packageIndexed": true,
>     "packageStatusExplaination": "A matching version of this tweak for this iOS version could not be found. Please submit a review if you choose to install.",
>     "id": "signing-certificate",
>     "commercial": false,
>     "packageInstalled": true,
>     "tweakCompatVersion": "0.1.5",
>     "shortDescription": "A Certificate to sign things with",
>     "latest": "0.0.1",
>     "author": "None",
>     "packageStatus": "Unknown"
>   },
>   "base64": "eyJhcmNoMzIiOmZhbHNlLCJwYWNrYWdlSWQiOiJzaWduaW5nLWNlcnRpZmljYXRlIiwiZGV2aWNlSWQiOiJpUGhvbmUxMCw2IiwidXJsIjoiaHR0cDpcL1wvY3lkaWEuc2F1cmlrLmNvbVwvcGFja2FnZVwvc2lnbmluZy1jZXJ0aWZpY2F0ZVwvIiwiaU9TVmVyc2lvbiI6IjEyLjQiLCJwYWNrYWdlVmVyc2lvbkluZGV4ZWQiOnRydWUsInBhY2thZ2VOYW1lIjoiU2lnbmluZyBDZXJ0aWZpY2F0ZSIsImNhdGVnb3J5IjoiU3lzdGVtIiwicmVwb3NpdG9yeSI6IihudWxsKSIsIm5hbWUiOiJTaWduaW5nIENlcnRpZmljYXRlIiwiaW5zdGFsbGVkIjoiMC4wLjEiLCJwYWNrYWdlSW5kZXhlZCI6dHJ1ZSwicGFja2FnZVN0YXR1c0V4cGxhaW5hdGlvbiI6IkEgbWF0Y2hpbmcgdmVyc2lvbiBvZiB0aGlzIHR3ZWFrIGZvciB0aGlzIGlPUyB2ZXJzaW9uIGNvdWxkIG5vdCBiZSBmb3VuZC4gUGxlYXNlIHN1Ym1pdCBhIHJldmlldyBpZiB5b3UgY2hvb3NlIHRvIGluc3RhbGwuIiwiaWQiOiJzaWduaW5nLWNlcnRpZmljYXRlIiwiY29tbWVyY2lhbCI6ZmFsc2UsInBhY2thZ2VJbnN0YWxsZWQiOnRydWUsInR3ZWFrQ29tcGF0VmVyc2lvbiI6IjAuMS41Iiwic2hvcnREZXNjcmlwdGlvbiI6IkEgQ2VydGlmaWNhdGUgdG8gc2lnbiB0aGluZ3Mgd2l0aCIsImxhdGVzdCI6IjAuMC4xIiwiYXV0aG9yIjoiTm9uZSIsInBhY2thZ2VTdGF0dXMiOiJVbmtub3duIn0=",
>   "chosenStatus": "working",
>   "notes": ""
> }
